[BaiduFilter]
APIKey = 'your_api_key_here'
SecretKey = 'your_secret_key_here'
AccessToken = ''
ExpiresIn = 0

[BaiduErnie]
APPID = ''
APIKey = ''
SecretKey = ''
Temperature = 0.95
TopP = 0.8
PenaltyScore = 1.0
Prompt = ''
AccessToken = ''
ExpiresIn = 0

[BaiduErnie.MemoryAndClean]
ShortMemoryTokenLimit = 500
CleanAll = true
CleanOne = false
